# Change these first
owner: Redish101 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Redish101博客
    url: https://redish101.github.io
   - name: 图床系统
    url: https://cdn.jsdelivr.net/gh/Redish101/redish101.github.io@gh-pages/img
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Redish101博客状态
  introTitle: "页面介绍"
  introMessage: 此页面为Redish101博客的状态检测页面，如有报错，请在[Redish101.github.io](https://github.com/redish101/redish101.github.io)仓库中提交issues
  navbar:
    - title: 博客首页
      href: /
    - title: 博客源代码
      href: https://github.com/Redish101/redish101.github.io
    - title: 构建日志
      href: https://github.com/Redish101/redish101.github.io/actions

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
